In [7]:
import wikipedia
import numpy as np
import pandas as pd
import math

In [52]:
data = pd.read_csv('../data/FinalSource_Real Cases.csv', sep=',',  error_bad_lines=False, encoding = 'ISO-8859-1')

In [53]:
def extract_company(url):
    try : 
        try : 
            company = url.split('www.')[1]
        except : 
            company = url.split('//')[1]
        
        company = company.split('.')[0]
        return company
    except : 
        return np.nan

In [54]:
data['company'] = data['URL'].apply(extract_company)

In [55]:
data.head()

,Date,Notify,URL,IP,Country,OS,WebServer,Encoding,Lang,company
0,1998-01-02,Team CodeZero,http://www.janet-jackson.com,NaN,UNKNOWN,Unknown,Unknown,utf-8,NaN,janet-jackson
1,1998-01-03,Feliz,http://cariari.ucr.ac.cr,NaN,COSTARICA,Unknown,Unknown,NaN,NaN,cariari
2,1998-01-04,Optiklenz(LOU),http://marin.k12.ca.us,NaN,UNITED STATES,Unknown,Unknown,iso-8859-1,Helvetica,marin
3,1998-01-04,Team CodeZero,http://www.dm.af.mil,NaN,AFGHANISTAN,Unknown,Unknown,utf-8,NaN,dm
4,1998-01-04,Team CodeZero,http://www.bolling.af.mil,NaN,AFGHANISTAN,Unknown,Unknown,windows-1252,Times New Roman,bolling

In [59]:
def lower(x) : 
    try : 
        x = x.lower()
        return x
    except : 
        return x
    
data['Country'].apply(lambda x : lower(x)).unique()

array(['unknown', 'costarica', 'united states', 'afghanistan', 'andorra',
       nan, 'sweden', 'netherlands', 'united kingdom', 'india', 'mexico',
       'italy', 'thailand', 'japan', 'brazil', 'australia', 'china',
       'malaysia', 'russian federation', 'germany', 'south africa',
       'pakistan', 'czech republic', 'argentina', 'belgium', 'denmark',
       'romania', 'colombia', 'france', 'canada', 'hungary', 'niue',
       'tonga', 'singapore', 'austria', 'slovenia', 'indonesia',
       'south korea', 'portugal', 'bolivia', 'taiwan', 'hong kong',
       'yugoslavia', 'norway', 'montenegro', 'switzerland', 'philippines',
       'panama', 'newzealand', 'peru', 'iran', 'honduras', 'niger',
       'nicaragua', 'turkey', 'saudiarabia', 'virginislands(british)',
       'ireland', 'americansamoa', 'kuwait', 'croatia', 'chile', 'spain',
       'cuba', 'burkinafaso', 'venezuela', 'lesotho', 'finland', 'israel',
       'puertorico', 'georgia', 'macedonia', 'greece', 'uruguay',
       'eritrea', 'haiti', 'qatar', 'luxembourg', 'srilanka', 'mongolia',
       'ukraine', 'bulgaria', 'morocco', 'slovakia', 'ghana', 'estonia',
       'guam', 'albania', 'paraguay', 'ecuador', 'poland', 'moldova',
       'suriname', 'elsalvador', 'lebanon', 'jordan',
       'northern mariana islands', 'egypt', 'tuvalu',
       'bosnia and herzegovina', 'gabon', 'united arabemirates',
       'barbados', 'lithuania', 'liechtenstein', 'nepal', 'togo', 'zambia',
       'guinea', 'vaticancitystate', 'armenia', 'turksandcaicosislands',
       'mauritius', 'mozambique', 'bhutan', 'iceland', 'macau', 'bahamas',
       'ascensionisland', 'algeria', 'caledonia', 'oman', 'bahrain',
       'latvia', 'kenya', 'seychelles', 'samoa', 'bermuda',
       'norfolkisland', 'iraq', 'trinidad and tobago',
       'libyanarabjamahiriya', 'antigua and barbuda', 'jamaica', 'malta',
       'san marino', 'senegal', 'burundi', 'monaco', 'kazakhstan',
       'botswana', 'cyprus', 'montserrat', 'tunisia', 'zimbabwe',
       'belarus', 'belize', 'bruneidarussalam', 'cameroon',
       'dominican republic', 'bangladesh', 'greenland', 'congo',
       'virginislands(u.s.)', 'faroe islands', 'namibia', 'kyrgyzstan',
       'micronesia', 'fiji', 'easttimor', 'capeverde', 'azerbaijan',
       'tajikistan', 'saotomeandprincipe', 'turkmenistan', 'madagascar',
       'netherlandsantilles', 'benin', 'saintkittsnevis', 'europe',
       'somalia', 'guatemala', 'vietnam', 'mauritania', 'serbia',
       'sri lanka', 'guernsey', 'united arab emirates', 'cambodia',
       'asia/pacific region', 'anonymous proxy', 'satellite provider',
       'syrian arab republic', 'palestinian territory', 'papua new guinea',
       'rwanda', 'united state', 'united kingd', 'russian fede',
       'viet nam', 'syrian arab', 'netherlands"', 'czech republ',
       'costa rica', 'new zealand"', 'taiwan, prov', 'macedonia, t',
       'moldova, rep', 'korea, repub', 'virgin islan', 'nigeria"',
       'iran, islami', 'european uni', 'french polyn', 'puerto rico',
       'cayman islan', 'new caledoni', 'saudi arabia', 'french polynesia',
       'european union', 'el salvador', 'virgin islands', 'cayman islands',
       'korea', 'new zealand', 'uzbekistan', 'new caledonia', 'yemen',
       'brunei darussalam', 'maldives', 'libyan arab jamahiriya',
       'nigeria', 'sudan', 'america', 'westeuro', 'easteuro',
       'southamerica', 'asia', 'oseania', 'middleeast', 'africa',
       'ethiopia', 'mali', 'tanzania', "cote d'ivoire", 'burkina faso',
       'vanuatu', 'malawi', 'uganda', 'cook islands', 'cape verde',
       "lao people's democratic republic"], dtype=object)

In [13]:
import json
import os
import glob
cwd = os.getcwd()
list_file = glob.glob("{}/norse_json/*.json".format(cwd))

In [40]:
def load_data(list_file):
    with open(list_file[0]) as json_data :
        data = pd.DataFrame.from_dict(json.load(json_data))

    for file in list_file[1:] : 
        with open(file) as json_data:
            data = pd.concat([data, pd.DataFrame.from_dict(json.load(json_data))])
    return data

In [36]:
data.head()

,attack_type,attacker,attacker_country,attacker_town,date,ip,target_country,target_town
0,unknown,Hostkey B.V.,NL,Amsterdam,2018-03-07T23:25:09.947865,185.70.186.148,AE,Dubai
1,microsoft-ds,Hangzhou Silan Microelectronice Co. Ltd,CN,Hangzhou,2018-03-07T23:25:09.947865,60.190.248.130,AE,Dubai
2,smtp,Microsoft Corporation,US,Redmond,2018-03-07T23:25:09.947865,157.56.111.250,US,DeKalbJunction
3,smtp,Microsoft Corporation,US,Redmond,2018-03-07T23:25:09.947865,207.46.100.254,US,DeKalbJunction
4,https,American National Insurance Co,US,LeagueCity,2018-03-07T23:25:09.947865,50.200.102.48,US,DeKalbJunction

In [48]:
mapping_country = {
    'NL' : 'netherlands', 
    'CN' : 'china', 
    'US' : 'united states', 
    'MX' : 'mexico', 
    'TR' : 'turkey', 
    'PK' : 'pakistan', 
    'HK' : 'hong kong', 
    'VN' : 'vietnam', 
    'RO' : 'roumania', 
    'IT' : 'italia', 
    'KR' : 'south korea',
    'JP' : 'japan', 
    'CH' : 'swiss', 
    'UA' : 'ukraine', 
    'ES' : 'spain', 
    'CZ' : 'czech republic', 
    'BR' : 'brazil', 
    'IN' : 'india', 
    'PH' : 'philippines', 
    'GB' : 'united kingdom', 
    'PL' : 'poland', 
    'FR' : 'france', 
    'IL' : 'israel', 
    'CA' : 'canada', 
    'CO' : 'colombia', 
    'DE' : 'germany', 
    'SA' : 'saudi arabia', 
    'AM' : 'armenia', 
    'BO' : 'bolivia', 
    'BG' : 'bulgaria', 
    'AR' : 'argentina', 
    'TW' : 'taiwan', 
    'MD' : 'moldova',
    'ID' : 'indonesia', 
    'BE' : 'belgium', 
    'TH' : 'thailand', 
    'PT' : 'portugal', 
    'EG' : 'egypt', 
    'CL' : 'chile', 
    'NZ' : 'new zealand', 
    'RU' : 'russia', 
    'CY' : 'cyprus', 
    'BM' : 'bermuda', 
    'MN' : 'mongolia',
    'IR' : 'ireland', 
    'BD' : 'bangladesh', 
    'SI' : 'slovenia', 
    'VE' : 'venezuela', 
    'AU' : 'australia', 
    'AE' : 'united arab emirates',
    'NO' : 'norway',
    'SG' : 'singapore',
    'IE' : 'ireland',
    'IS' : 'iceland',
    'AT' : 'austria'    
}

In [49]:
data = load_data(list_file)
data['attacker_country'] = data['attacker_country'].apply(lambda x : x.replace(x, mapping_country[x]))
data['target_country'] = data['target_country'].apply(lambda x : x.replace(x, mapping_country[x]))